---
# defaults file for role-base

base_config_repos: yes

#base_dns_servers:
#  - 8.8.8.8
#  - 8.8.4.4
#base_dns_search: 'domain1.com domain2.net'
#base_dns_domain: 'domain.com'

#base_timezone: 'Europe/Madrid'

#base_ntp_servers:
#  - hora.roa.es

#base_swap_size: 16384
#base_swap_mem: 8192

#base_extra_packages:
#  - sysstat
#  - telnet
#  - net-tools

# Repositories
base_repos:
  - name: 
    description: 
    baseurl:
    file: '
    enabled:
    distribution: 
    release: 



