# Añadir Grupo operaciones SD
- name: Creating operaciones group
  group:
    name: operaciones
    gid: 668
    state: present

# Añadir el usuario 'operador' con el uid 668, crear home, shell en /bin/bash miembro del grupo operaciones y con clave ssh
- name: Creating operador user
  user:
    name: operador
    uid: 668
    group: operaciones
    createhome: yes
    shell: /bin/bash
