---
# tasks file for role-base

- name: Set DNS servers
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  when: base_dns_servers is defined

- name: Configure repositories
  include: repos.yml
  when: base_config_repos

- name: Set time zone
  timezone: name={{ base_timezone }}
  when: base_timezone is defined

- name: Set hostname
  hostname: name={{ base_hostname }}
  when: base_hostname is defined

- name: Set root password
  user: name='root' password={{ base_root_password | password_hash('sha512') }} update_password=always
  when: base_root_password is defined

- name: Set ntp sync
  include: ntp.yml
  when: base_ntp_servers is defined

- name: Modify swap space
  include: swap.yml
  when: base_swap_mem is defined and base_swap_size is defined and ansible_memtotal_mb>{{ base_swap_mem }} and ansible_swaptotal_mb<{{ base_swap_size|int - 32 }}

- name: Install extra packages
  yum: name={{ item }}
  with_items: "{{ base_extra_packages | default() }}"
  when: base_extra_packages is defined
